### ISSUE TITLE
IE 9.0 Compatibility

### ISSUE THREAD

**Issue by mui-org** [cdotyone/mochaui#49] opened 2010-06-25 12:57 UTC
Prepare for IE 9.0 Canvas control.  Stop including excanvas_r43.js for IE 9.0?

**Comment by plamen79** [comment] 2011-04-06 09:11
Real Disaster is the problem with IE9. Jquerry already patched their library to support IE9. When can we expect our beloved MochaUI to do so ?

**Comment by jer0m** [comment] 2011-04-18 08:09
Hello,

I currently use Mochaui 0.9.7 in my project and I'm really embarassed with IE9. I already modified your code to be compatible with Canvas in native mode. BUT, we face a really big problem with z-index inside the windows. 

We are unable to click inside the window to fill a form for example. Do you have an idea about the problem or a workaround ?

Thank you

N.B: We are on Mootools 1.3 with compatibility mode.

Jérôme

Edit: We found the bug. It was not a z-index issue but a bug in setupEvents who stopped the mouse event for all trident browsers including IE9

**Comment by blq** [comment] 2011-04-19 15:27
In my (albeit old fork) I found that I needed to force the z-index of the  window element "cache.canvasControlsEl" to 0. 
In the current trunk this seems to correspond to the "cache.canvas" element, class="mochaCanvas"  (see Window.js/_insertWindowElements() ).
Combined with a quick-hack sniff for the availability of  the "G_vmlCanvasManager" I could then disable excanvas for IE9 and thinks worked.

// Fredrik

**Comment by cdotyone** [comment] 2011-05-02 03:04
I will look at this and add it to both the 0.98 and 1.0 branches.

**Comment by plamen79** [comment] 2011-05-27 15:16
I have the same case : I have modified the Dock.js in Mocha 0.9.6 at line 127 and all the rest corresponding lines 
"if (Browser.Engine.trident && MUI.ieSupport == 'excanvas'){
G_vmlCanvasManager.initElement(canvas);" to 
if (Browser.Engine.trident && navigator.appVersion.split(' ')[3].replace(';','')!= "9.0" && MUI.ieSupport == 'excanvas'){
G_vmlCanvasManager.initElement(canvas);
This make execution possible in IE9 but with the following bugs :
1.We are unable to click inside the window to fill a form (un-click-able text fields)- gettin in with "tab" works
2. Close,Minimize, Maximize buttons does not work - they are drawled properly but mouse cursor does not change getting over them and they are un-click-able.
I have dowlnloaded from git  repository version 1.0 but it is rather different from the current version of Mocha 0.9.6 that i used in the production site. Any idea for workaround with the current version ?

**Comment by cdotyone** [comment] 2011-05-27 19:36
I have been swamped with my day job lately.  I will see what I can do.
-Chris

**Comment by jer0m** [comment] 2011-05-27 20:16
Hi plamen,

We had this bug of unclickable windows too. It's due to this part of code around line 720 in window.js:

```
    if (this.options.type == 'window'){
        windowEl.addEvent('mousedown', function(e) {
            if (Browser.Engine.trident && !Browser.ie9) {
                new Event(e).stop();
            }
            MUI.focusWindow(windowEl);
            if (windowEl.getStyle('top').toInt() < -this.options.shadowBlur) {
                windowEl.setStyle('top', -this.options.shadowBlur);
            }
        }.bind(this));
    }
```

The original code blocks mouse events in windows for ALL ie including IE9. We added "&& !Browser.ie9" (mootools syntax) and it's working like a charm ;)

Hope this helps
Jerome

**Comment by plamen79** [comment] 2011-06-01 06:43
Hi famicity,

Thank you very much for your advice! It really helped a lot. Now text fields are click-able and our site is nearly fully functional in IE9. There is only one headache left behind:
The close, minimize and maximize buttons have no on hover event and are not been able to click on. Closing windows inside the browser is available through 'Esc' key , but buttons are not functioning at all (only for IE9). Do you have any idea what might cause the problem ?
Regards
Plamen

**Comment by jer0m** [comment] 2011-06-01 08:38
Hi plamen,

You must not include the excanvas js file for IE9. We put this:
    
You also need to put other exceptions for IE9 on code. We put these ones:
In dock.js line 138:
            if ((Browser.Engine.trident && !Browser.ie9) && MUI.ieSupport == 'excanvas'){
                G_vmlCanvasManager.initElement(canvas);
            }
In window.js line 1248:
        if (this.options.useCanvas == true && (Browser.Engine.trident && !Browser.ie9)) {
//..
        }
line 1280:
if ((Browser.Engine.trident && !Browser.ie9) && MUI.ieSupport == 'excanvas'){
//..
}
line 1327:
if ((Browser.Engine.trident && !Browser.ie9)  && MUI.ieSupport == 'excanvas'){
//..
}

Hope this helps.

Jerome

**Comment by StephenSegari** [comment] 2011-06-15 02:32
famicity,

I'm having the same problem as plamen.  All code has been updated to check for Browser.ie9 and I am conditionally including the excanvas.js file, like you suggested.  For the life of me, I cannot get the close, minimize, and maximize buttons to work correctly in IE9.  Any additional help would be appreciated.

Thanks,
Stephen

**Comment by StephenSegari** [comment] 2011-06-15 02:59
Forgot to add, I'm running MooTools v1.3.2 and MochaUI 0.9.7

**Comment by plamen79** [comment] 2011-06-15 07:05
Hi Famicity, hi Stephen  - I am using mootools 1.2.5 and MochaUI 0.9.6. Exactly the same problem. Close, Min and Max buttons does not work. Famicity advice did help in terms of - text fields to be clickable and usable - but that was all I am still struggling to make the production site working properly in IE9. The worst thing is that in the development tool of IE9 the current condition of the code does not   return any errors or warnings. As per my observation the function from window.js : "insertWindowElements: function()" does not work properly especially this part :

if (MUI.ieSupport == 'excanvas' && navigator.appVersion.split(' ')[3].replace(';','')!= "9.0"){
                G_vmlCanvasManager.initElement(cache.canvasEl);
                cache.canvasEl = this.windowEl.getElement('.mochaCanvas');
            }
        }

```
    cache.controlsEl = new Element('div', {
        'id': id + '_controls',
        'class': 'mochaControls'
    }).inject(cache.overlayEl, 'after');

    if (options.useCanvasControls == true){
        cache.canvasControlsEl = new Element('canvas', {
            'id': id + '_canvasControls',
            'class': 'mochaCanvasControls',
            'width': 14,
            'height': 14
        }).inject(this.windowEl);

        if ((Browser.Engine.trident && navigator.appVersion.split(' ')[3].replace(';','')!= "9.0") && MUI.ieSupport == 'excanvas'){
            G_vmlCanvasManager.initElement(cache.canvasControlsEl);
            cache.canvasControlsEl = this.windowEl.getElement('.mochaCanvasControls');
        }
    }

    if (options.closable){
        cache.closeButtonEl = new Element('div', {
            'id': id + '_closeButton',
            'class': 'mochaCloseButton mochaWindowButton',
            'title': 'Close'
        }).inject(cache.controlsEl);
    }

    if (options.maximizable){
        cache.maximizeButtonEl = new Element('div', {
            'id': id + '_maximizeButton',
            'class': 'mochaMaximizeButton mochaWindowButton',
            'title': 'Maximize'
        }).inject(cache.controlsEl);
    }

    if (options.minimizable){
        cache.minimizeButtonEl = new Element('div', {
            'id': id + '_minimizeButton',
            'class': 'mochaMinimizeButton mochaWindowButton',
            'title': 'Minimize'
        }).inject(cache.controlsEl);
    }
```

Any Ideas would be highly appreciated.

Best Regards
Plamen

**Comment by StephenSegari** [comment] 2011-06-15 14:53
I was able to get the close button working with a CSS hack.  The problem is that the div is empty, or I guess IE9 sees it as empty.  So here's what I did (notice the style and html attributes added):

if (options.closable){
            cache.closeButtonEl = new Element('div', {
                'id': id + '_closeButton',
                'class': 'mochaCloseButton mochaWindowButton',
                'title': 'Close',
                'style': 'font-size: 1000px; overflow: hidden;',
                'html': '&nbsp;'
            }).inject(cache.controlsEl);
        }

This method would work for any of the other control icons as well I would assume.

**Comment by plamen79** [comment] 2011-06-16 07:18
Thanks Stephen - this method does not give any positive results for me. Are you sure that you are not running the IE9 in compatibility mode ? (in this mode it works fine - all buttons are usable )

**Comment by cdotyone** [comment] 2011-08-10 04:14
I will not be updating the 0.9.6 branch for IE9 compatibility.  If someone gets it working.  I will commit their changes.

**Comment by cdotyone** [comment] 2011-08-10 04:15
Canvas controls not used for IE9 as of today.

**Closed as completed by cdotyone** 2011-08-10 04:14 UTC
Labels: Planned Feature

**Comment by SeanKorea** [comment] 2011-08-30 10:51
Window.css

.mocha.replaced, .mochaTitlebar.replaced, .mochaMinimizeButton.replaced, .mochaMaximizeButton.replaced, .mochaCloseButton.replaced {
    background-color: transparent !important;
}

change to

.mochaMinimizeButton.replaced, .mochaMaximizeButton.replaced, .mochaCloseButton.replaced{
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
    filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=0);
    opacity: 0;
    -moz-opacity: 0;
}

.mocha.replaced, .mochaTitlebar.replaced{
    background-color: transparent !important;
}
